
name: Image Upload

on: push

jobs:
    upload:
        name: Image Upload Job
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - run: pip install python-dotenv
            - run: python3 azure_blob_file_upload_test.py
